In [1]:
import torch
import numpy as np

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [5]:
np_array

array([[1, 2],
       [3, 4]])

In [6]:
x_np

tensor([[1, 2],
        [3, 4]])

In [7]:
tensor = torch.rand(3, 4)

In [8]:
tensor

tensor([[0.5103, 0.7795, 0.3464, 0.0375],
        [0.1106, 0.2268, 0.7335, 0.9653],
        [0.4033, 0.4413, 0.7420, 0.7734]])

In [9]:
tensor.shape, tensor.dtype, tensor.device

(torch.Size([3, 4]), torch.float32, device(type='cpu'))

In [10]:
tensor[0]

tensor([0.5103, 0.7795, 0.3464, 0.0375])

In [11]:
tensor[:, 0]

tensor([0.5103, 0.1106, 0.4033])

In [12]:
tensor[...,-1]

tensor([0.0375, 0.9653, 0.7734])

In [13]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)

In [14]:
t1

tensor([[0.5103, 0.7795, 0.3464, 0.0375, 0.5103, 0.7795, 0.3464, 0.0375, 0.5103,
         0.7795, 0.3464, 0.0375],
        [0.1106, 0.2268, 0.7335, 0.9653, 0.1106, 0.2268, 0.7335, 0.9653, 0.1106,
         0.2268, 0.7335, 0.9653],
        [0.4033, 0.4413, 0.7420, 0.7734, 0.4033, 0.4413, 0.7420, 0.7734, 0.4033,
         0.4413, 0.7420, 0.7734]])

In [18]:
tensor

tensor([[0.5103, 0.7795, 0.3464, 0.0375],
        [0.1106, 0.2268, 0.7335, 0.9653],
        [0.4033, 0.4413, 0.7420, 0.7734]])

In [16]:
y1 = tensor @ tensor.T

In [17]:
y1

tensor([[0.9894, 0.5235, 0.8358],
        [0.5235, 1.5336, 1.4356],
        [0.8358, 1.4356, 1.5061]])

In [19]:
y2 = tensor.matmul(tensor.T)

In [20]:
y2

tensor([[0.9894, 0.5235, 0.8358],
        [0.5235, 1.5336, 1.4356],
        [0.8358, 1.4356, 1.5061]])

In [21]:
agg = tensor.sum()

In [22]:
agg

tensor(6.0700)

In [23]:
agg_item = agg.item()

In [24]:
agg_item

6.0699591636657715